default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [ "--maxkb=800" ]
        exclude: "poetry.lock"
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        name: black Formatting
-   repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0
    hooks:
    -   id: upgrade-type-hints
